version: "3"

services:
  server:
    container_name: server_models_ai4b
    build: 
      context: ./backend
    working_dir: /server
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - ./backend:/server
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --reload"